- name: Documentação do Kubernetes preparado para o Azure Arc
  href: index.yml
- name: Descrição geral
  items:
    - name: Acerca do Kubernetes preparado para o Arc
      href: overview.md
- name: Guias de procedimentos
  items:
    - name: Ligar ao Azure Arc
      items:
        - name: Ligar cluster
          href: connect-cluster.md
        - name: Incluir principal de serviço
          href: create-onboarding-service-principal.md
    - name: Gerir
      items:
        - name: Implementar configurações com o GitOps
          href: use-gitops-connected-cluster.md
        - name: Implementar gráficos Helm com o GitOps
          href: use-gitops-with-helm.md
        - name: Impor o GitOps com o Azure Policy
          href: use-azure-policy.md
        - name: Monitorizar com o Azure Monitor para contentores
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Políticas de controlo de acesso com o Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Implementar cargas de trabalho de IoT
          href: deploy-azure-iot-edge-workloads.md
    - name: Resolução de problemas
      href: Troubleshooting.md
- name: Referência
  items:
    - name: Incorporações do Azure Policy
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
- name: Recursos
  items:
    - name: Introdução rápida ao Azure Arc
      href: 'https://github.com/microsoft/azure_arc'